// swift-tools-version: 5.10
import PackageDescription

let package = Package(
    name: "WalletCore",
    defaultLocalization: "en",
    platforms: [
        .iOS(.v17),
    ],
    products: [
        .library(name: "WalletCore", targets: ["WalletCore"]),
    ],
    dependencies: [
        .package(url: "https://github.com/mischa-hildebrand/AlignedCollectionViewFlowLayout", branch: "master"),
        .package(url: "https://github.com/horizontalsystems/BitcoinCashKit.Swift", exact: "3.0.1"),
        .package(url: "https://github.com/horizontalsystems/BitcoinCore.Swift", exact: "3.2.0"),
        .package(url: "https://github.com/horizontalsystems/BitcoinKit.Swift", exact: "3.0.1"),
        .package(url: "https://github.com/horizontalsystems/Chart.Swift", exact: "3.0.2"),
        .package(url: "https://github.com/horizontalsystems/Checkpoints", exact: "1.0.29"),
        .package(url: "https://github.com/Coeur/CollectionViewCenteredFlowLayout", from: "1.0.4"),
        .package(url: "https://github.com/krzyzanowskim/CryptoSwift", from: "1.9.0"),
        .package(url: "https://github.com/horizontalsystems/DashKit.Swift", exact: "3.1.0"),
        .package(url: "https://github.com/johnxnguyen/Down", from: "0.11.0"),
        .package(url: "https://github.com/horizontalsystems/ECashKit.Swift.git", exact: "3.0.2"),
        .package(url: "https://github.com/horizontalsystems/Eip20Kit.Swift", exact: "2.1.0"),
        .package(url: "https://github.com/horizontalsystems/EvmKit.Swift", exact: "2.5.0"),
        .package(url: "https://github.com/horizontalsystems/FeeRateKit.Swift", exact: "2.1.1"),
        .package(url: "https://github.com/horizontalsystems/HCaptcha-ios-sdk.git", exact: "1.0.0"),
        .package(url: "https://github.com/horizontalsystems/HdWalletKit.Swift", exact: "1.3.1"),
        .package(url: "https://github.com/horizontalsystems/Hodler.Swift", exact: "2.0.3"),
        .package(url: "https://github.com/horizontalsystems/HsCryptoKit.Swift", exact: "1.3.2"),
        .package(url: "https://github.com/horizontalsystems/HsToolKit.Swift.git", exact: "2.0.5"),
        .package(url: "https://github.com/kishikawakatsumi/KeychainAccess.git", from: "4.0.0"),
        .package(url: "https://github.com/onevcat/Kingfisher.git", from: "8.6.2"),
        .package(url: "https://github.com/horizontalsystems/LitecoinKit.Swift", exact: "3.0.2"),
        .package(url: "https://github.com/horizontalsystems/MarketKit.Swift", exact: "3.6.12"),
        .package(url: "https://github.com/horizontalsystems/MoneroKit.Swift", exact: "0.2.8"),
        .package(url: "https://github.com/horizontalsystems/NftKit.Swift", exact: "2.0.2"),
        .package(url: "https://github.com/tristanhimmelman/ObjectMapper", exact: "4.2.0"),
        .package(url: "https://github.com/horizontalsystems/OneInchKit.Swift", exact: "3.0.4"),
        .package(url: "https://github.com/reown-com/reown-swift", exact: "2.0.0"),
        .package(url: "https://github.com/ReactiveX/RxSwift.git", from: "5.1.3"),
        .package(url: "https://github.com/horizontalsystems/SectionsTableView.Swift", exact: "1.0.0"),
        .package(url: "https://github.com/SnapKit/SnapKit.git", from: "5.7.1"),
        .package(url: "https://github.com/horizontalsystems/solana-kit-ios.git", exact: "1.0.2"),
        .package(url: "https://github.com/daltoniam/Starscream", from: "3.1.2"),
        .package(url: "https://github.com/horizontalsystems/StellarKit.Swift", exact: "1.2.0"),
        .package(url: "https://github.com/horizontalsystems/TonConnectAPI", exact: "1.0.0"),
        .package(url: "https://github.com/horizontalsystems/TonKit.Swift", exact: "1.2.1"),
        .package(url: "https://github.com/horizontalsystems/TronKit.Swift.git", exact: "1.5.1"),
        .package(url: "https://github.com/horizontalsystems/UIExtensions.Swift", exact: "1.0.2"),
        .package(url: "https://github.com/horizontalsystems/UniswapKit.Swift", exact: "3.2.0"),
        .package(url: "https://github.com/horizontalsystems/ZcashLightClientKit", exact: "2.6.0-alpha.4-hs.1"),
    ],
    targets: [
        .target(
            name: "WalletCore",
            dependencies: [
                .product(name: "AlignedCollectionViewFlowLayout", package: "AlignedCollectionViewFlowLayout"),
                .product(name: "BitcoinCashKit", package: "BitcoinCashKit.Swift"),
                .product(name: "BitcoinCore", package: "BitcoinCore.Swift"),
                .product(name: "BitcoinKit", package: "BitcoinKit.Swift"),
                .product(name: "Chart", package: "Chart.Swift"),
                .product(name: "Checkpoints", package: "Checkpoints"),
                .product(name: "CollectionViewCenteredFlowLayout", package: "CollectionViewCenteredFlowLayout"),
                .product(name: "CryptoSwift", package: "CryptoSwift"),
                .product(name: "DashKit", package: "DashKit.Swift"),
                .product(name: "Down", package: "Down"),
                .product(name: "ECashKit", package: "ECashKit.Swift"),
                .product(name: "Eip20Kit", package: "Eip20Kit.Swift"),
                .product(name: "EvmKit", package: "EvmKit.Swift"),
                .product(name: "FeeRateKit", package: "FeeRateKit.Swift"),
                .product(name: "HCaptcha", package: "HCaptcha-ios-sdk"),
                .product(name: "HdWalletKit", package: "HdWalletKit.Swift"),
                .product(name: "Hodler", package: "Hodler.Swift"),
                .product(name: "HsCryptoKit", package: "HsCryptoKit.Swift"),
                .product(name: "HsToolKit", package: "HsToolKit.Swift"),
                .product(name: "KeychainAccess", package: "KeychainAccess"),
                .product(name: "Kingfisher", package: "Kingfisher"),
                .product(name: "LitecoinKit", package: "LitecoinKit.Swift"),
                .product(name: "MarketKit", package: "MarketKit.Swift"),
                .product(name: "MoneroKit", package: "MoneroKit.Swift"),
                .product(name: "ZanoKit", package: "MoneroKit.Swift"),
                .product(name: "NftKit", package: "NftKit.Swift"),
                .product(name: "ObjectMapper", package: "ObjectMapper"),
                .product(name: "OneInchKit", package: "OneInchKit.Swift"),
                .product(name: "ReownRouter", package: "reown-swift"),
                .product(name: "ReownWalletKit", package: "reown-swift"),
                .product(name: "RxSwift", package: "RxSwift"),
                .product(name: "RxCocoa", package: "RxSwift"),
                .product(name: "RxRelay", package: "RxSwift"),
                .product(name: "SectionsTableView", package: "SectionsTableView.Swift"),
                .product(name: "SnapKit", package: "SnapKit"),
                .product(name: "SolanaKit", package: "solana-kit-ios"),
                .product(name: "Starscream", package: "Starscream"),
                .product(name: "StellarKit", package: "StellarKit.Swift"),
                .product(name: "TonConnectAPI", package: "TonConnectAPI"),
                .product(name: "TonKit", package: "TonKit.Swift"),
                .product(name: "TronKit", package: "TronKit.Swift"),
                .product(name: "UIExtensions", package: "UIExtensions.Swift"),
                .product(name: "UniswapKit", package: "UniswapKit.Swift"),
                .product(name: "ZcashLightClientKit", package: "ZcashLightClientKit"),
            ],
            resources: [
                .process("Resources/Localizable.xcstrings"),
            ]
        ),
    ]
)
