import UIKit

class SendTheme {
    static let titleHeight: CGFloat = 38
    static let titleBottomMargin: CGFloat = 5
    static let scanQRWidth: CGFloat = 40
    static let qrSideSize: CGFloat = 24
    static let sendTitleFont = UIFont.cryptoHeadline
    static let twinHeight: CGFloat = 180
    static let inputBorderWidth: CGFloat = 1
    static let cornerRadius: CGFloat = 8
    static let inputBorderColor = UIColor.cryptoLightGray
    static let sendButtonSideMargin: CGFloat = 16
    static let inputTintColor = UIColor.cryptoYellow
    static let sendButtonBottomMargin: CGFloat = 16
    static let sendButtonBottomMarginShrink: CGFloat = 10
    static let referenceInputTopMargin: CGFloat = 22
    static let inputTextColor = UIColor.cryptoDark
    static let inactiveInputTextColor = UIColor.cryptoGray
    static let inputFont = UIFont.cryptoBody2
    static let sendButtonItemHeight: CGFloat = 90
    static let sendButtonItemHeightShrink: CGFloat = 75
    static let timeLabelFont = UIFont.cryptoHeadline
    static let timeLabelColor = UIColor.black
    static let buttonCornerRadius: CGFloat = 4
    static let inputCornerRadius: CGFloat = 6
    static let sendButtonHeight: CGFloat = 50
    static let addressHeight: CGFloat = 47
    static let referenceInputHeight: CGFloat = 44
    static let timeLabelTopMargin: CGFloat = 24
    static let buttonFont = UIFont.cryptoBody2
    static let buttonBorderColor = UIColor.cryptoSteel50
    static let feeLabelColor = UIColor.cryptoGray
    static let feeLabelFont = UIFont.cryptoHeadline
    static let buttonTextDictionary: RespondButton.Style = [.active: UIColor.cryptoDark, .selected: UIColor.cryptoDark, .disabled: UIColor.cryptoSilver]
    static let inputFieldsGap: CGFloat = 24
    static let sliderTintColor = UIColor.cryptoGreen
    static let amountHeight: CGFloat = 72
    static let amountInputHeight: CGFloat = 46
    static let separatorBackground = UIColor.cryptoLightGray
    static let moreButtonTextColor = UIColor.cryptoGreen
    static let moreButtonTextSelectedColor = UIColor.cryptoGreenPressed
    static let separatorHeight: CGFloat = 1
    static let exchangeValueTextColor = UIColor.cryptoSilver
    static let exchangeValueFont = UIFont.cryptoCaption3
    static let errorColor = UIColor.cryptoRed
    static let errorFont = UIFont.cryptoCaption3
    static let addressTopMargin: CGFloat = 17

    static let sideMargin: CGFloat = 16
    static let smallMargin: CGFloat = 8
    static let buttonSideMargin: CGFloat = 6
    static let smallestMargin: CGFloat = 4
    static let buttonTitleMargin: CGFloat = 10
    static let currencyDropImageLeftMargin: CGFloat = 5
    static let backButtonTopMargin:CGFloat = 24
    static let currencyDropImageSize = CGSize(width: 6, height: 5)
    static let currencyDropImageRightMargin: CGFloat = 8
}
