lane :dev_t do |options|
  prepare_environment

  cert(username: ENV['ITUNES_CONNECT_USERNAME'], team_id: options[:dp_team_id])
  sigh(app_identifier: "io.horizontalsystems.bank-wallet.dev.testnet", force: true, adhoc: true, username: ENV['ITUNES_CONNECT_USERNAME'], team_id: options[:dp_team_id])
  gym(scheme: "Bank Dev T", export_method: "ad-hoc", silent: true, clean: true, export_options: { compileBitcode: false })

  upload_to_hockey(options[:hockey_api_token])
end

lane :dev do |options|
  prepare_environment

  cert(username: ENV['ITUNES_CONNECT_USERNAME'], team_id: options[:dp_team_id])
  sigh(app_identifier: "io.horizontalsystems.bank-wallet.dev", force: true, adhoc: true, username: ENV['ITUNES_CONNECT_USERNAME'], team_id: options[:dp_team_id])
  gym(scheme: "Bank Dev", export_method: "ad-hoc", silent: true, clean: true, export_options: { compileBitcode: false })

  upload_to_hockey(options[:hockey_api_token])
end

def prepare_environment
  sh("cp ../BankWallet/BankWallet/Configuration/Development.template.xcconfig ../BankWallet/BankWallet/Configuration/Development.xcconfig")
  sh("cp ../BankWallet/BankWallet/Configuration/Production.template.xcconfig ../BankWallet/BankWallet/Configuration/Production.xcconfig")

  sh("rm -rf ~/Library/Developer/Xcode/Archives/**")
  sh("rm -rf ~/Library/MobileDevice/Provisioning\\ Profiles/**")

  reset_git_repo(force: true)
  clear_derived_data

  increment_build_number(
      build_number: ENV['BUILD_NUMBER'],
      xcodeproj: "./BankWallet/BankWallet.xcodeproj"
  )

  cocoapods(repo_update: true)
end

def upload_to_hockey(api_token)
  hockey(
    api_token: api_token,
    notes: last_git_commit[:message]
  )
end
