name: Deploy to Firebase

on:
  push:
    branches: [ version/* ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_and_deploy:
    name: Build and Deploy to Firebase
    runs-on: macos-26

    steps:
      - name: Setup Xcode to 26.4
        uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # v1.7.0
        with:
          xcode-version: '26.4'

      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Ruby v3
        uses: ruby/setup-ruby@984c0c890880bbf811283d6f09c4607c62d210a4 # v1.323.0
        with:
          ruby-version: 3.3.9
          bundler-cache: true

      - name: Setup Rust and Cargo
        uses: dtolnay/rust-toolchain@02cb101ec7c40f2c49e1d9714d64511d8e1b74de # master 2026-09-12
        with:
          toolchain: stable

      - name: Install Lipo via Cargo
        run: cargo install cargo-lipo

      - name: Add iOS targets to Rust
        run: rustup target add aarch64-apple-ios x86_64-apple-ios

      - name: Load match deploy key
        uses: webfactory/ssh-agent@e83874834305fe9a4a2997156cb26c5de65a8555 # v0.10.0
        with:
          ssh-private-key: ${{ secrets.MATCH_DEPLOY_KEY }}

      - name: Run Fastlane (build, upload to AppCenter)
        uses: maierj/fastlane-action@182983d8f94bad9884001c03c1c2786f4c7165ed # v3.2.0
        with:
          lane: dev
        env:
          FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 120
          BUILD_NUMBER: ${{ github.run_number }}
          APP_ID: ${{ secrets.APP_ID }}
          TEMP_KEYCHAIN_USER: ${{ secrets.TEMP_KEYCHAIN_USER }}
          TEMP_KEYCHAIN_PASSWORD: ${{ secrets.TEMP_KEYCHAIN_PASSWORD }}
          APPLE_ISSUER_ID: ${{ secrets.APPLE_ISSUER_ID }}
          APPLE_KEY_ID: ${{ secrets.APPLE_KEY_ID }}
          APPLE_KEY_CONTENT: ${{ secrets.APPLE_KEY_CONTENT }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}

          XCCONFIG_ARBISCAN_API_KEYS: ${{ secrets.XCCONFIG_DEV_ARBISCAN_API_KEYS }}
          XCCONFIG_BASESCAN_API_KEYS: ${{ secrets.XCCONFIG_DEV_BASESCAN_API_KEYS }}
          XCCONFIG_BSCSCAN_API_KEYS: ${{ secrets.XCCONFIG_DEV_BSCSCAN_API_KEYS }}
          XCCONFIG_CHAINALYSIS_API_KEY: ${{ secrets.XCCONFIG_DEV_CHAINALYSIS_API_KEY }}
          XCCONFIG_DEFIYIELD_API_KEY: ${{ secrets.XCCONFIG_DEV_DEFIYIELD_API_KEY }}
          XCCONFIG_ERA_ZKSYNC_API_KEYS: ${{ secrets.XCCONFIG_DEV_ERA_ZKSYNC_API_KEYS }}
          XCCONFIG_ETHERSCAN_API_KEYS: ${{ secrets.XCCONFIG_DEV_ETHERSCAN_API_KEYS }}
          XCCONFIG_FTMSCAN_API_KEYS: ${{ secrets.XCCONFIG_DEV_FTMSCAN_API_KEYS }}
          XCCONFIG_GNOSISSCAN_API_KEYS: ${{ secrets.XCCONFIG_DEV_GNOSISSCAN_API_KEYS }}
          XCCONFIG_HASHDIT_API_KEY: ${{ secrets.XCCONFIG_DEV_HASHDIT_API_KEY }}
          XCCONFIG_HS_PROVIDER_API_KEY: ${{ secrets.XCCONFIG_DEV_HS_PROVIDER_API_KEY }}
          XCCONFIG_JUPITER_API_KEY: ${{ secrets.XCCONFIG_DEV_JUPITER_API_KEY }}
          XCCONFIG_MERKLE_API_PATH: ${{ secrets.XCCONFIG_DEV_MERKLE_API_PATH }}
          XCCONFIG_ONE_INCH_API_KEY: ${{ secrets.XCCONFIG_DEV_ONE_INCH_API_KEY }}
          XCCONFIG_OPEN_SEA_API_KEY: ${{ secrets.XCCONFIG_DEV_OPEN_SEA_API_KEY }}
          XCCONFIG_OPTIMISM_ETHERSCAN_API_KEYS: ${{ secrets.XCCONFIG_DEV_OPTIMISM_ETHERSCAN_API_KEYS }}
          XCCONFIG_POLYGONSCAN_API_KEYS: ${{ secrets.XCCONFIG_DEV_POLYGONSCAN_API_KEYS }}
          XCCONFIG_ROBINHOOD_API_KEYS: ${{ secrets.XCCONFIG_DEV_ROBINHOOD_API_KEYS }}
          XCCONFIG_SNOWTRACE_API_KEYS: ${{ secrets.XCCONFIG_DEV_SNOWTRACE_API_KEYS }}
          XCCONFIG_SOLANA_ALCHEMY_API_KEYS: ${{ secrets.XCCONFIG_DEV_SOLANA_ALCHEMY_API_KEYS }}
          XCCONFIG_TRONGRID_API_KEYS: ${{ secrets.XCCONFIG_DEV_TRONGRID_API_KEYS }}
          XCCONFIG_TWITTER_BEARER_TOKEN: ${{ secrets.XCCONFIG_DEV_TWITTER_BEARER_TOKEN }}
          XCCONFIG_UNSTOPPABLE_DOMAINS_API_KEY: ${{ secrets.XCCONFIG_DEV_UNSTOPPABLE_DOMAINS_API_KEY }}
          XCCONFIG_USWAP_API_KEY: ${{ secrets.XCCONFIG_DEV_USWAP_API_KEY }}
          XCCONFIG_WALLET_CONNECT_V2_PROJECT_KEY: ${{ secrets.XCCONFIG_DEV_WALLET_CONNECT_V2_PROJECT_KEY }}

          XCCONFIG_MAYA_AFFILIATE: ${{ secrets.XCCONFIG_DEV_MAYA_AFFILIATE }}
          XCCONFIG_MAYA_AFFILIATE_BPS: ${{ secrets.XCCONFIG_DEV_MAYA_AFFILIATE_BPS }}
          XCCONFIG_ONE_INCH_COMMISSION: ${{ secrets.XCCONFIG_DEV_ONE_INCH_COMMISSION }}
          XCCONFIG_ONE_INCH_COMMISSION_ADDRESS: ${{ secrets.XCCONFIG_DEV_ONE_INCH_COMMISSION_ADDRESS }}
          XCCONFIG_THORCHAIN_AFFILIATE: ${{ secrets.XCCONFIG_DEV_THORCHAIN_AFFILIATE }}
          XCCONFIG_THORCHAIN_AFFILIATE_BPS: ${{ secrets.XCCONFIG_DEV_THORCHAIN_AFFILIATE_BPS }}

      - name: Upload dSYM files
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: success()
        with:
          name: dsym-files-build-${{ github.run_number }}
          path: "**/*.dSYM.zip"
          retention-days: 90
