name: Notify PR to Telegram

on:
  pull_request:
    branches: [ version/* ]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send telegram message
        uses: appleboy/telegram-action@v1.1.1
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.event.pull_request.html_url }}

            Title: ${{ github.event.pull_request.title }}
            Author: ${{ github.actor }}
