name: Notify PR to Telegram

on:
  pull_request:
    branches: [ version/* ]

jobs:
  notify:
    if: ${{ !startsWith(github.head_ref, 'l10n_version/') }}
    runs-on: ubuntu-latest

    steps:
      - name: Send telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{secrets.TELEGRAM_TO}}
          token: ${{secrets.TELEGRAM_TOKEN}}
          args: |
            ${{ github.event.pull_request.html_url }}

            Title   : ${{github.event.pull_request.title}}
            Author  : @${{github.actor}}
            Event   : ${{ github.event_name }}
